AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template for the Bank Expenditure Scraper
Parameters:
  BankName:
    Type: String
  DopplerToken:
    Type: String
    NoEcho: true
  DopplerConfig:
    Type: String
    Default: dev_aws
Resources:
  ChromiumLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: chromium-layer
      Description: Layer containing @sparticuz/chromium
      ContentUri: s3://bank-scraper-deployments-390844784861/97ce217f73ea3dc7bbf059896d549e77
      CompatibleRuntimes:
      - nodejs20.x
    Metadata:
      BuildMethod: nodejs
  ScraperFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: bank-scraper
      Handler: index.handler
      Runtime: nodejs20.x
      MemorySize: 1024
      Timeout: 120
      CodeUri: s3://bank-scraper-deployments-390844784861/5c2d48bdef9ab1dde53167524f633b45
      Layers:
      - Ref: ChromiumLayer
      Environment:
        Variables:
          BANK_NAME_DEFAULT:
            Ref: BankName
          DOPPLER_TOKEN:
            Ref: DopplerToken
          DOPPLER_CONFIG:
            Ref: DopplerConfig
      Policies:
      - AWSLambdaBasicExecutionRole
Outputs:
  LambdaFunctionArn:
    Description: ARN of the Scraper Lambda function
    Value:
      Fn::GetAtt:
      - ScraperFunction
      - Arn
